[project]
channels = ["conda-forge"]
name = "already-installed"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = "3.13.*"
typing-extensions = "*"
pydantic-core = "2.26.0"
